#!/bin/sh

#PBS -N mendel
#PBS -e pbs.err
#PBS -o pbs.log
#PBS -q batch
#PBS -l nodes=2:ppn=2

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo This jobs runs on the following processors:
echo `cat $PBS_NODEFILE`

NPROCS=`wc -l < $PBS_NODEFILE`
echo This job has allocated $NPROCS nodes

NP=4

#/usr/local/bin/mpirun -machinefile $PBS_NODEFILE -np $NP ./mendel > mendel.out 
/usr/local/bin/mpirun -np $NP ./mendel > mendel.out 

